#!/bin/bash
conf_file="$HOME/suckless/Assest.conf"
if [[ ! -f "$conf_file" ]]; then
    notify-send "Configuration file $conf_file does not exist."
    exit 1
fi
source "$conf_file"

pkg=$(dmenu < /dev/null -p "What do you want to add ?")

if [[ -z "$pkg" ]]; then
    exit 1
fi

if pacman -Sp "$pkg" &>/dev/null; then

    if [[ ! " ${DPN[@]} " =~ " ${pkg} " ]]; then
        
        sed -i "/^DPN=(/s/)/ \"$pkg\")/" "$HOME/suckless/Assest.conf"
        notify-send "Package $pkg has been added to Assest.conf"
    else
        notify-send "Package $pkg already exists in Assest.conf"
    fi
else
    notify-send "$pkg is not a valid package name"
fi




