#!/bin/bash
source "$HOME/.local/bin/themes.conf"
clock=$(date '+%I')

case "$clock" in
	"00") icon="󱑊" ;;
	"01") icon="󱐿" ;;
	"02") icon="󱑀" ;;
	"03") icon="󱑁" ;;
	"04") icon="󱑂" ;;
	"05") icon="󱑃" ;;
	"06") icon="󱑄" ;;
	"07") icon="󱑅" ;;
	"08") icon="󱑆" ;;
	"09") icon="󱑇" ;;
	"10") icon="󱑈" ;;
	"11") icon="󱑉" ;;
	"12") icon="󱑊" ;;
esac

case $BUTTON in
	3) setsid -f "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

date "+^c$c0^| ^c$c8^%b %d ^c$c1^%a ^c$c2^$icon ^c$c8^'%I:%M'%p"

