#!/usr/bin/env bash

# Ensure that the directory exists and is not empty
files=($XDG_RUNTIME_DIR/clipmenu.6.$USER/*)


# Find the newest file
newest=${files[0]}
for f in "${files[@]}"; do
    if [[ $f -nt $newest ]]; then
        newest=$f
    fi
done

# Extract and play the YouTube URL using mpv
if url=$(grep --max-count=1 --only-matching --perl-regexp "https:\/\/(www\.)?youtube\.com\/[^\s\"()<>]*" "$newest"); then
    # Ensure mpv is installed and available
    if command -v mpv > /dev/null; then
        kitty --hold -e mpv "$url"
    else
        notify-send "mpv is not installed."
    fi
else
    notify-send "No YouTube URL found"
fi
