#!/bin/bash

if [[ "$BUTTON" == "1" ]]; then
    choice=$(echo -e "Github\nChatgpt\nYoutube" | dmenu -p "What website do you want to open : ")

    case "$choice" in
        "Github")
            url="https://github.com/Melal1?tab=repositories"
            ;;
        "Chatgpt")
            url="https://chatgpt.com"
            ;;
        "Youtube")
            url="https://youtube.com"
            ;;
        *)
            exit 1
            ;;
    esac

    if [[ -n "$url" ]]; then
        xdg-open "$url" &>/dev/null
    fi

fi

echo " | ^c#6E6E6E^ "







