version = 2
final_space = true
console_title_template = "{{.PWD}}"
[[blocks]]
type = 'rprompt'
alignment = 'right'
overflow = 'hidden'
newline = true
  [[blocks.segments]]
    type = 'executiontime'
    style = 'plain'
    foreground = 'cyan'
    background = 'transparent'
    template = '{{if gt .Code 0}}<red>took</> {{ .FormattedMs }}{{else}}<yellow>took</> {{ .FormattedMs }}{{end}}'

    [blocks.segments.properties]
      threshold = 5000
      style = "round"
      always_enabled = true


[[blocks]]
  type = 'prompt'
  alignment = 'left'

# [[blocks.segments]] 
# type = 'text' 
# style = 'diamond'
# template = ' '
# background = 'black'
# foreground = 'blue'
# leading_diamond = ''
# trailing_diamond = ''

  [[blocks.segments]]
    type = 'git'
    style = 'diamond'
    foreground = 'black'
    background = 'white'
    leading_diamond = ''
    trailing_diamond = ''
    template = '{{.HEAD}}{{ if or (.Working.Changed) (.Staging.Changed) }}<magenta>*</>{{end}}{{ if gt .Behind 0 }}<red>{{ .BranchStatus }}󱞣</>{{ end }}{{ if gt .Ahead 0 }}<black>󱞿{{ .BranchStatus }}</>{{ end }}'
    [blocks.segments.properties]
      branch_icon = ''
      commit_icon = ''
      fetch_status = true
      fetch_upstream_icon = true
      branch_ahead_icon = ''
      branch_behind_icon = ''
      # [blocks.segments.properties.mapped_branches]
[[blocks.segments]] 
type = 'text' 
style = 'plain'
template = ''
background = 'transparent'
foreground = 'yellow'
[[blocks.segments]]
type = 'path'
style = 'plain'
foreground = 'gray'
background = 'trasnparent'
[blocks.segments.properties]
style = 'full'


[[blocks]]
type = 'prompt'
alignment = 'left'
newline = true

[[blocks.segments]]
type = 'text' 
style = 'plain'
template = '❯'
background = 'transparent'
foreground_templates = [
  '{{if gt .Code 0}}red{{end}}',
  '{{if eq .Code 0}}green{{end}}',


]
[transient_prompt]
  foreground_templates = [
    '{{if gt .Code 0}}magenta{{end}}',
    '{{if eq .Code 0}}gray{{end}}',
  ]
  background = 'transparent'
  template = '❯ '
  
 [palette] 
